Repository TUM-Dev/eat-api, pull requests merged in 2021-12, with the labels that each got.

#66 Manual worflow trigger
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .github/workflows/publish_en.yml
Labels: enhancement

#69 GH Pages linting
  .eslintrc.js
  .github/workflows/ci-website.yml
  .gitignore
  .pre-commit-config.yaml
  css/bulma-prefers-dark.min.css
  css/bulma.min.css
  css/leaflet.css
  index.html
  js/app.js
  js/leaflet.js
  js/mithril.min.js
Labels: enhancement, CI, pages

#71 Website - UI Fixes - Location/Map
  css/styles.css
  js/app.js
Labels: enhancement, pages

#72 Website - introduction of JS modules
  .eslintrc.js
  .pre-commit-config.yaml
  index.html
  js/app.js
  js/components/date-selection.js
  js/components/ingredients.js
  js/components/location-selection.js
  js/components/menu.js
  js/external.js
  js/leaflet.js
  js/mithril.min.js
  js/modules/date-util.js
  js/modules/url-util.js
Labels: enhancement, pages

#78 Revert "Website - introduction of JS modules"
  .eslintrc.js
  .pre-commit-config.yaml
  index.html
  js/app.js
  js/components/date-selection.js
  js/components/ingredients.js
  js/components/location-selection.js
  js/components/menu.js
  js/external.js
  js/leaflet.js
  js/mithril.min.js
  js/modules/date-util.js
  js/modules/url-util.js
Labels: bug, pages

#80 Website - Quick Bugfix: Make menus viewable again
  js/app.js
Labels: bug, pages

#82 Website - Fix labels
  js/app.js
Labels: enhancement, pages

#84 Website - JS Modules
  .eslintrc.js
  .pre-commit-config.yaml
  index.html
  js/app.js
  js/components/date-selection.js
  js/components/labels.js
  js/components/location-selection.js
  js/components/menu.js
  js/leaflet.js
  js/mithril.min.js
  js/modules/date-utils.js
  js/modules/url-utils.js
Labels: enhancement, pages

#91 Website - Bugfix modules loading: lib folder was ignored by .gitignore
  .eslintrc.js
  index.html
  js/app.js
  js/components/date-selection.js
  js/components/labels.js
  js/components/location-selection.js
  js/components/menu.js
  js/external/leaflet.js
  js/external/leaflet.module.js
  js/external/mithril.min.js
  js/external/mithril.module.js
  js/modules/url-utils.js
Labels: bug, pages

#88 Add queue status field to the canteens and set it for "mensa-garching"
  src/entities.py
Labels: enhancement

#90 Get prices for side dishes, correct prices for leopoldstr
  src/menu_parser.py
Labels: enhancement

#75 Ingredient selection for website
  js/components/labels.js
  js/components/menu.js
  js/modules/url-utils.js
Labels: enhancement

#85 Add abbreviations to the labels
  src/entities.py
Labels: enhancement

#95 Update base_url to only include relative path
  src/entities.py
Labels: enhancement, pages

#93 Remove duplicate mentioning of canteens in parse script
  scripts/parse.sh
  scripts/parse_canteen_list.py
Labels: enhancement
