Repository TUM-Dev/eat-api, pull requests merged in 2021-11, with the labels that each got.

#34 refactor StudentenwerkMenuParserTest
  src/test/test_menu_parser.py
  src/test/test_util.py
Labels: enhancement

#40 Migrate to use pyproject.toml as much as possible
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .pre-commit-config.yaml
  .pylintrc
  Dockerfile
  README.md
  poetry.lock
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  setup.cfg
Labels: enhancement

#41 Add dependabot
  .github/dependabot.yml
Labels: enhancement, CI

#38 Improvements of the GH-Pages Website
  css/bulma-prefers-dark.min.css
  css/bulma.css
  css/bulma.min.css
  css/styles.css
  index.html
  js/app.js
  js/mithril.min.js
Labels: enhancement

#37 Translate dish titles
  .github/workflows/publish_en.yml
  README.md
  poetry.lock
  pyproject.toml
  scripts/parse.sh
  src/cli.py
  src/main.py
  src/util.py
Labels: enhancement

#55 Replace moment.js with native functions
  index.html
  js/app.js
  js/moment.min.js
Labels: bug, enhancement

#57 Further website improvments
  js/app.js
Labels: enhancement

#58 Add map integration to website
  css/images/layers-2x.png
  css/images/layers.png
  css/images/marker-icon-2x.png
  css/images/marker-icon.png
  css/images/marker-shadow.png
  css/leaflet.css
  css/styles.css
  index.html
  js/app.js
  js/leaflet.js
Labels: enhancement
