Repository TUM-Dev/eat-api, pull requests merged in 2022-01, with the labels that each got.

#59 Website language switcher
  css/styles.css
  index.html
  js/app.js
  js/components/labels.js
  js/components/language-selection.js
  js/components/location-selection.js
  js/components/menu.js
  js/components/translate.js
  js/external/i18next.min.js
  js/external/i18next.module.js
  js/external/i18nextBrowserLanguageDetector.min.js
  js/external/i18nextBrowserLanguageDetector.module.js
  js/modules/translation.js
  js/modules/url-utils.js
Labels: enhancement

#100 Adapt reference files for tests to prices for "Beilagen"
  src/test/assets/studentenwerk/mensa-arcisstr/reference/combined.json
  src/test/assets/studentenwerk/mensa-garching/reference/combined.json
  src/test/assets/studentenwerk/mensa-garching/reference/week_37.json
  src/test/assets/studentenwerk/mensa-garching/reference/week_38.json
  src/test/assets/studentenwerk/stubistro-grosshadern/reference/combined.json
Labels: bug

#103 [website] Fix URL for accessing menu data with different languages
  js/components/menu.js
Labels: bug, pages

#104 [website] symbols and abbreviations for labels
  js/components/labels.js
Labels: enhancement

#101 Add documentation via swagger
  .github/workflows/swagger.yml
  README.md
  openapi.yml
Labels: documentation

#113 Minify JSON
  scripts/combine.py
  scripts/reformat.py
  src/enum_json_creator.py
  src/main.py
  src/utils/json_util.py
Labels: enhancement

#105 Introduce static open hours for canteens
  openapi.yml
  src/entities.py
Labels: enhancement

#115 [Website] Show opening hours
  css/styles.css
  js/app.js
  js/components/labels.js
  js/components/location-selection.js
  js/components/modal.js
  js/components/opening-hours.js
  js/modules/date-utils.js
  js/modules/translation.js
Labels: enhancement, pages
